# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('short_description', models.CharField(max_length=256)),
                ('cover_image', models.ImageField(upload_to=b'')),
                ('episode_link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
    ]
