# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='cover_image_square',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='Square Cover Image (600x600)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cover_image',
            field=models.ImageField(upload_to=b'', verbose_name='Cover Image (810x450)'),
        ),
    ]
