# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20160325_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='length',
            field=models.TimeField(default='01:02:03'),
            preserve_default=False,
        ),
    ]
