# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 00:06
from __future__ import unicode_literals

from django.db import migrations
import podcast.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20160522_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='cover_image',
            field=podcast.fields.CompressedImageField(image_quality=90, resize_to=(0, 300), upload_to='', verbose_name='Cover Image (810x450)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cover_image_square',
            field=podcast.fields.CompressedImageField(blank=True, image_quality=90, resize_to=(0, 300), upload_to='', verbose_name='Square Cover Image (600x600)'),
        ),
    ]
